class MainConfig:
    DB_CONFIG = {
        "connection_url" : "mongodb+srv://sukoon_user:Tcks8x7wblpLL9OA@cluster0.o7vywoz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0",
    }

    SMS_API_CONFIG = {
        "userid": "2000241133",
        "password": "FJGtU6wH",
        "method": "SendMessage",
        "msg": "Dear user, use __otp__ as One Time Password generated by Three Dots & Dash to log in to your Sukoon.Love account.",
        "msg_type": "TEXT",
        "auth_scheme": "plain",
        "v": "1.1",
        "format": "text"
    }
    
    SMS_API_URL = "https://enterprise.smsgupshup.com/GatewayAPI/rest"

    PUSH_NOTIFICATION_API = {
        "URL": "https://fcm.googleapis.com/v1/projects/sukoonlove-007/messages:send",
        "ACCESS_TOKEN": "AIzaSyAMJotLhCHDZQav-pI3xwh94zK9f2A62r8"
    }
