name: Flask API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
        
      - name: Set up Environment
        run: |
          export GITHUB_PAT=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
          echo "machine github.com login $GITHUB_PAT" > ~/.netrc
          git config --global credential.helper store

      - name: Install Dependencies
        run: |
          cd backend_amp/amplify/backend/function/gamesProcessor/src
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pipenv pytest pytest-flask awsgi boto3

      - name: Initialize submodules
        run: |
          git submodule deinit --all --force
          git submodule update --init --recursive

      - name: Run Tests
        run: |
          cd backend_amp/amplify/backend/function/gamesProcessor/src
          source venv/bin/activate
          export ENV=local
          pytest tests/